[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.format-rust]
args          = [ "fmt", "--all", "--", "--emit=files" ]
command       = "cargo"
install_crate = "rustfmt"
workspace     = false

[tasks.format-toml]
args          = [ "format" ]
command       = "taplo"
install_crate = "taplo-cli"
workspace     = false

[tasks.format]
dependencies = [ "format-rust", "format-toml" ]
workspace    = false
