env_files = [ { path = ".env" } ]

[env]
ALICE                                = "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
CONTRACT_PATH                        = "./target/ink/flipper.contract"
FERDIE                               = "5CiPPseXPECbkjWCa6MnjNokrgYjMqmKndv2rSnekmSK2DjL"
GAS_LIMIT                            = 999999999999
SALT                                 = "0x000001"
STORAGE_DEPOSIT_LIMIT                = 10000000000000

[tasks.clean_env]
script = "rm -rf .env && touch .env"

[tasks.build]
dependencies  = [ "clean_env" ]
args          = [ "contract", "build" ]
command       = "cargo"
install-crate = "cargo-contract"

[tasks.registry_params_part_one]
script = '''
printf "%s " ${FERDIE} > /tmp/upload.params
'''

[tasks.registry_params_part_two]
script = '''
printf "{\"codeTxt\":\"%s\",\"bytes\":\"%s\",\"author\":{\"account\":\"%s\",\"feesPerSingleUse\":%d},\"meta\":{\"metadataVersion\":\"1.0\",\"name\":\"bojopartyman\",\"contractType\":4,\"version\":\"1.0\"}}" $(jq -r .source.hash ${CONTRACT_PATH}) $(jq -r .source.wasm ${CONTRACT_PATH}) ${FERDIE} 1000000000000 >> /tmp/upload.params
'''

[tasks.registry_upload]
dependencies = [ "clean_env", "registry_params_part_one", "registry_params_part_two" ]
script = '''
  hash=$(polkadot-js-api \
  --ws ws://localhost:9944 \
  --seed //Alice \
  --params /tmp/upload.params \
  --sudo tx.contractsRegistry.addNewContract \
  | jq -r '.addNewContract.events[1].event.data[1] | select( . != null )') && \
  echo "CONTRACT_HASH=${hash}" > .env && \
  echo ${hash}
'''

[tasks.transfer]
script = '''
    printf \
        "%s %d" \
        "$FERDIE" \
        1000000000000 \
        > /tmp/balance.params && \
    polkadot-js-api \
        --ws ws://localhost:9944 \
        --seed //Alice \
        --params /tmp/balance.params \
        tx.balances.transfer
'''

[tasks.registry_instantiate]
dependencies = [ "registry_upload" ]
script = '''
    printf \
        "%d %d %d %s %s %s" \
        "0" \
        ${GAS_LIMIT} \
        ${STORAGE_DEPOSIT_LIMIT} \
        ${CONTRACT_HASH} \
        $(jq -r .V3.spec.constructors[0].selector ${CONTRACT_PATH}) \
        $SALT \
        > /tmp/flipper.params && \
    polkadot-js-api \
        --ws ws://localhost:9944 \
        --seed //Alice \
        --params /tmp/flipper.params tx.contracts.instantiate
'''

[tasks.instantiate]
script = '''
    printf \
        "%d %d %d %s %s %s" \
        "0" \
        ${GAS_LIMIT} \
        ${STORAGE_DEPOSIT_LIMIT} \
        $(jq -r .source.wasm ${CONTRACT_PATH}) \
        $(jq -r .V3.spec.constructors[0].selector ${CONTRACT_PATH})00000000 \
        $SALT \
        > /tmp/flipper_instantiate.params && \
    address=$(polkadot-js-api \
        --ws ws://localhost:9944 \
        --seed //Alice \
        --params /tmp/flipper_instantiate.params tx.contracts.instantiateWithCode \
        | jq -r '.instantiateWithCode.events[1].event.data[0] | select( . != null )') && \
        echo "CONTRACT_ADDRESS=${address}" > .env && \
        echo ${address}
'''

[tasks.call]
script = '''
    printf \
        "%s %d %d %d %s" \
        ${CONTRACT_ADDRESS} \
        "0" \
        ${GAS_LIMIT} \
        ${STORAGE_DEPOSIT_LIMIT} \
        $(jq -r .V3.spec.messages[1].selector ${CONTRACT_PATH})00 \
        > /tmp/flipper_call.params && \
    polkadot-js-api \
        --ws ws://localhost:9944 \
        --seed //Alice \
        --params /tmp/flipper_call.params tx.contracts.call
'''

[tasks.instantiate_and_call]
dependencies = [ "instantiate", "call" ]
