export default {
  types: {
    GatewayVendor: {
      _enum: ['Substrate', 'Ethereum'],
    },
    GatewayType: {
      _enum: { ProgrammableInternal: 'u32', ProgrammableExternal: 'u32', TxOnly: 'u32' },
    },
    GatewayGenesisConfig: {
      modules_encoded: 'Option<Bytes>',
      extrinsics_version: 'u8',
      genesis_hash: 'Bytes',
    },
    GatewaySysProps: {
      ss58_format: 'u16',
      token_symbol: 'Bytes',
      token_decimals: 'u8',
    },
    AllowedSideEffect: '[u8; 4]',
    BlockNumber: 'u64',
    Compose: {
      name: 'Vec<u8>',
      code_txt: 'Vec<u8>',
      exec_type: 'Vec<u8>',
      dest: 'AccountId',
      value: 'Balance',
      bytes: 'Vec<u8>',
      input_data: 'Vec<u8>',
    },
    CircuitOutboundMessage: {
      name: 'Bytes',
      module_name: 'Bytes',
      method_name: 'Bytes',
      sender: 'Option<Bytes>',
      target: 'Option<Bytes>',
      arguments: 'Vec<Bytes>',
      expected_output: 'Vec<GatewayExpectedOutput>',
      extra_payload: 'Option<ExtraMessagePayload>',
    },
    GatewayExpectedOutput: {
      _enum: {
        Storage: {
          key: 'Vec<Vec<u8>>',
          value: 'Vec<Option<Bytes>>',
        },
        Events: { signatures: 'Vec<Bytes>' },
        Extrinsic: {
          block_height: 'Option<u64>',
        },
        Output: { output: 'Bytes' },
      },
    },
    ProofTriePointer: {
      _enum: {
        State: 0,
        Transaction: 1,
        Receipts: 2,
      },
    },
    GatewayPointer: {
      id: 'ChainId',
      vendor: 'GatewayVendor',
      gateway_type: 'GatewayType',
    },
    ExtraMessagePayload: {
      signer: 'Bytes',
      module_name: 'Bytes',
      method_name: 'Bytes',
      call_bytes: 'Bytes',
      signature: 'Bytes',
      extra: 'Bytes',
      tx_signed: 'Bytes',
      custom_payload: 'Option<Bytes>',
    },
    ContractActionDesc: {
      action_id: 'Hash',
      target_id: 'Option<TargetId>',
      to: 'Option<AccountId>',
    },
    TargetId: '[u8; 4]',
    SideEffect: {
      target: 'TargetId',
      prize: 'BalanceOf',
      ordered_at: 'BlockNumber',
      encoded_action: 'Bytes',
      encoded_args: 'Vec<Bytes>',
      signature: 'Bytes',
      enforce_executioner: 'Option<AccountId>',
    },
    SideEffectId: 'Hash',
    ConfirmedSideEffect: {
      err: 'Option<Bytes>',
      output: 'Option<Bytes>',
      encoded_effect: 'Bytes',
      inclusion_proof: 'Option<Bytes>',
      executioner: 'AccountId',
      received_at: 'BlockNumber',
      cost: 'Option<BalanceOf>',
    },
    FullSideEffect: {
      input: 'SideEffect',
      confirmed: 'Option<ConfirmedSideEffect>',
    },
    XtxId: 'Hash',
    EventSignature: 'Vec<u8>',
    EventName: 'Vec<u8>',
  },
  result_status: 'Vec<u8>',
  Xtx: {
    estimated_worth: 'BalanceOf',
    current_worth: 'BalanceOf',
    requester: 'AccountId',
    escrow_account: 'AccountId',
    payload: 'Vec<u8>',
    current_step: 'u32',
    steps_no: 'u32',
    current_phase: 'u32',
    current_round: 'u32',
    schedule: 'XtxSchedule<AccountId,BlockNumber,Hash,BalanceOf>',
    phases_blockstamps: '(BlockNumber, BlockNumber)',
  },
  XtxSchedule: {
    result_status: 'Vec<u8>',
    phases_blockstamps: '(BlockNumber, BlockNumber)',
  },
  ProofType: {
    _enum: {
      FullValue: 0,
      MerklePath: 1,
    },
  },
  StepConfirmation: {
    step_index: 'u8',
    value: 'Bytes',
    proof: 'Proof',
    outbound_event: 'GatewayOutboundEvent',
  },
  GatewayOutboundEvent: {
    id: 'GatewayOutboundEventId',
    signature: 'Option<Vec<u8>>',
    namespace: 'Vec<u8>',
    name: 'Vec<u8>',
    data: 'Bytes',
    proof: 'Option<Proof>',
    args_abi: 'Vec<Type>',
    args_encoded: 'Vec<Bytes>',
    gateway_pointer: 'GatewayPointer',
  },
  GatewayOutboundEventId: 'u64',
  SideEffectsDFD: 'Vec<u8>',
  GenericDFD: 'Vec<u8>',
};
