export const EXECUTOR = "EXECUTOR";
export const LOG_LEVEL = "LOG_LEVEL";
export const LOG_PRETTY = "LOG_PRETTY";
export const CIRCUIT_SIGNER_KEY = "CIRCUIT_SIGNER_KEY";
export const ETHEREUM_PRIVATE_KEY = "ETHEREUM_PRIVATE_KEY";
export const CIRCUIT_WS_ENDPOINT = "CIRCUIT_WS_ENDPOINT";
export const RELAYCHAIN_SIGNER_KEY = "RELAYCHAIN_SIGNER_KEY";
export const PROCESS_BATCHES = "PROCESS_BATCHES";
