[tasks.test-sdk-std]
args      = [ "test", "--features", "std" ]
command   = "cargo"
workspace = false

[tasks.test-sdk]
args      = [ "test" ]
command   = "cargo"
workspace = false

[tasks.test-parallel]
run_task = { name = [ "test-sdk-std", "test-sdk" ], parallel = true }
