[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.fixtures]
script = '''
for file in ./fixtures/*.sol
do
  solc -o ./fixtures --overwrite --bin --ast-compact-json --asm $file
done
'''
workspace = false
